---
l: 90.0
difficulty: 1
spinningAlpha: false
linearBeta: false
spinningBeta: false
linearAlpha: false
numAlphaPowerups: 5
numGammaMolecules: 5
numAlphaBlockers: 5
numGammaBlockers: 5
numSigmaMolecules: 5
numSigmaPowerups: 5
numAlphaMolecules: 5
numOfSigmaAtoms: 5
numBetaBlockers: 5
numBetaMolecules: 5
numOfAlphaAtoms: 5
numOfBetaAtoms: 5
numOfGammaAtoms: 5
numBetaPowerups: 5
numGammaPowerups: 5
numSigmaBlockers: 5
